language: java
deploy:
  provider: heroku
  api_key:
    secure: Y86a7Gmf8TrpIllNUFGMMP4jSP9ZtMRRQZP5kNP2Q4x6Y1Fc/s/EgxBGjpSPOim+sfOudHNWVx3KmayO+2US4yD39LGlWH8plHAARaYD/U6+WxL3E9zt4zBtfnLOa8bEDhZXiL/ie0k3+/2JCafuW3+snXOA4ygfaAQrM9wJlQRO+XtxNLocO2EQM6GQ1rV6L52W2krX+82YYIuZFTAsmAe9iDlMNDkB2sA1SMU6PWQab2+542qGYpkE82kC7DH+1q5nSNdLcDbb/V6XaWdxF4nu+Jr6lhzF/OYgyYGE0Q3OTKT47ikgW1hVx45D784zmbYEV1UTKP4srG1nZZypO2wn14ztx0uKvSuq7F3WwaJH0IeXd1I8GgyuFzaoV5+GUWSbSpTWAsAWlQ++QvpjthrxrgyQGQpYkmsaO3VBgVf0Uv6mnOTorUaw9W9z+LVfK/PsKLoenAUkHzXqwsV0jocpyxpG9nd9Uu0YcdClVVclSFgykk996QQ7rl4BzFpuLu9DszxoaPau/mBLNjvn5Fw2FqZfos3gxMaJQ2VpVJ52rhT5SkYt6hubIrbblrgH0y2/H3L1H5Tdtn8nb7wk9SLwB8KjgWFXfWUhdgCwIVdlVyvcpSgHArnoqqlKwrJkoLnb32VtWEaQkhl6oRD2RbHjCrnqu4MmiXjUNpBY4jY=
  app: guarded-island-73737

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1c618d55-c886-4a3b-9ef5-5738572f98cb

install:
  - "mvn install -s settings.xml -Dmaven.javadoc.skip=true -B -V"